### ISSUE TITLE
[TEST] VM related test cases failed on Cypress pipeline

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1196]
## What's the test to develop? Please describe
Below test cases are failing on Cypress test

1. Stop VM Negative
2. Schedule VM on the Node which is Enable Maintenance Mode
3. Create VM with existing volume

**Comment by khushboo-rancher** [comment]
@TachunLin Please add logs for the test cases failure if you have them

**Comment by TachunLin** [comment]
For test plan `Stop VM Negative`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The failure log indicate the vm stays in `Running` state
```
AssertionError: Timed out retrying after 600000ms: expected '<td.col-badge-state-formatter>' to contain 'Running'
    at eval (webpack:///./utils/components/cru-resource.po.ts:254:156)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/d960f5e8-8ade-4d80-86b4-16c1e70eb382)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/virtualmachines/node-scheduling.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/virtualmachines/node-scheduling.spec.ts#L11-L51

**Comment by TachunLin** [comment]
For test plan `Stop VM Negative`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The failure log indicate can't find node with name `harvester-node-0` 
```
AssertionError: Timed out retrying after 240000ms: expected '<ul#vs15__listbox.vs__dropdown-menu>' to contain 'harvester-node-0'
    at eval (webpack:///./pageobjects/virtualmachine.po.ts:119:64)
    at VmsPage.checkSpecificNodes (webpack:///./pageobjects/virtualmachine.po.ts:119:17)
    at Context.eval (webpack:///./testcases/virtualmachines/scheduling.spec.ts:24:8)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/ea73ee05-1267-44f4-8cd6-b31da36a67dd)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/virtualmachines/scheduling.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/virtualmachines/scheduling.spec.ts#L16-L40

**Comment by TachunLin** [comment]
For test plan `Create VM with existing volume`, according to the [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240329-061037-1747c15/index.html) 

* The context table can't find the vm name contains `use-existing-volume`
```
AssertionError: Timed out retrying after 240000ms: expected '<td>' to contain 'use-existing-volume'
    at Context.eval (webpack:///./pageobjects/volume.po.ts:84:27)
```

* The failure screenshot
![image](https://github.com/harvester/tests/assets/29251855/3ebc6010-65c8-4a4e-bb98-3a91f5f829d7)


* The failure comes from the following lines of code 
  - File: `../cypress/testcases/virtualmachines/virtual-machine.spec.ts`
  - Line: https://github.com/harvester/tests/blob/1747c1598b79047aaa261e9fa7fd2c626d4af0a9/cypress/testcases/virtualmachines/virtual-machine.spec.ts#L114-L193

**Comment by TachunLin** [comment]
According to the latest cypress test job on main Jenkins:
http://jenkins.provo.rancherlabs.com/job/harvester-cypress-test/65/console

On the related test report:
https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240624-032931-ceb811e/index.html

The cypress test PASS the following cases:

1. Stop VM Negative
2. Schedule VM on the Node which is Enable Maintenance Mode

![image](https://github.com/harvester/tests/assets/29251855/d0d47ab7-4486-48bd-8eca-83c78387f41f)

While cypress test FALED on the test case:
3. Create VM with existing volume
![image](https://github.com/harvester/tests/assets/29251855/5a1319b6-2fa4-44b5-9d22-8ab4adc71768)

**Comment by khushboo-rancher** [comment]
@torchiaf If the fix is working fine on the daily run, feel free to close it.
