### ISSUE TITLE
[BUG][DevOps]Fix CI/harvester-installer Jenkins restart issue

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#657]
Current Loadout:
```
            .-/+oossssoo+/-.               ubuntu@test-jenkins-ci-main-node 
        `:+ssssssssssssssssss+:`           -------------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: SYS-5018A-FTN4 123456789 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-56-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 day, 20 hours, 9 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 700 (dpkg), 4 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Atom C2758 (8) @ 2.400GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 02:00.0 ASPEED Technology, Inc. ASPEED Graphics Family 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 293MiB / 32077MiB 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/                              
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

Issue:
```
fatal: [master]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": false,
            "enabled": null,
            "force": null,
            "masked": null,
            "name": "jenkins",
            "no_block": false,
            "scope": "system",
            "state": "restarted"
        }
    },
    "msg": "Unable to restart service jenkins: Job for jenkins.service failed because the control process exited with error code.\nSee \"systemctl status jenkins.service\" and \"journalctl -xeu jenkins.service\" for details.\n"
}

```
Running provisioning scripts.

**Comment by irishgordo** [comment]
`journalctl -u jenkins | tail -n 50`

```
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:72)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at hudson.cli.CLI.plainHttpConnection(CLI.java:391)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at hudson.cli.CLI._main(CLI.java:320)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11962]:         at hudson.cli.CLI.main(CLI.java:102)
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: jenkins.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: jenkins.service: Failed with result 'exit-code'.
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: Failed to start Jenkins Continuous Integration Server.
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: jenkins.service: Scheduled restart job, restart counter is at 4.
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: Stopped Jenkins Continuous Integration Server.
Dec 14 19:29:42 test-jenkins-ci-main-node systemd[1]: Starting Jenkins Continuous Integration Server...
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]: java.net.ConnectException: Connection refused (Connection refused)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.Socket.connect(Socket.java:609)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/java.net.Socket.connect(Socket.java:558)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:72)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at hudson.cli.CLI.plainHttpConnection(CLI.java:391)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at hudson.cli.CLI._main(CLI.java:320)
Dec 14 19:29:42 test-jenkins-ci-main-node jenkins[11981]:         at hudson.cli.CLI.main(CLI.java:102)
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: jenkins.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: jenkins.service: Failed with result 'exit-code'.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: Failed to start Jenkins Continuous Integration Server.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: jenkins.service: Scheduled restart job, restart counter is at 5.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: Stopped Jenkins Continuous Integration Server.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: jenkins.service: Start request repeated too quickly.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: jenkins.service: Failed with result 'exit-code'.
Dec 14 19:29:43 test-jenkins-ci-main-node systemd[1]: Failed to start Jenkins Continuous Integration Server.

```

**Comment by irishgordo** [comment]
Occasionally the plugins are failing on provisioning too for some reason :/
